name: DNS Migration

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Python requirements
        run: |
          pip install boto3 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
    

      - name: Extract DNS records from Route 53
        run: python3 extract/export_route53_to_json.py

      - name: Run Terraform 
        run: |
            cd terraform
            terraform init
            terraform plan -out=tfplan  
            terraform apply -auto-approve tfplan
